### ISSUE TITLE
Add middle mouse button

### ISSUE THREAD

**Issue by BubiBalboa** [dessant/scroll-zoom#1]
Is it possible to add the middle mouse button to this addon? I find it very intuitive to press down on the mouse wheel to zoom pages.

Thanks for the addon. Very useful!

**Comment by dessant** [comment]
Thanks for the suggestion, I think this would be a great feature to have.

**Comment by dessant** [comment]
I gave this feature a try by holding down the scroll wheel on some mouses and scrolling. It took some effort to scroll while keeping the wheel pressed down, and it made my finger hurt a bit after a couple of uses. It also puts a lot of stress on the wheel, which might cause it to break sooner.

I'll close this for now as it seems to be a feature that could be harmful to users and their devices.
