### ISSUE TITLE
Scroll Zoom breaks Google search pages

### ISSUE THREAD

**Issue by nollinvoyd** [dessant/scroll-zoom#11]
**System**

* OS name: Windows 
* OS version: 10 Pro
* Browser name: Chrome
* Browser version:  95.0.4638.69
* Extension version: 1.1.1
* Mouse:  Logitech m-310

**Bug description**

Scroll Zoom interferes with all mouse functions on all Google search pages.  Extensive mouse function lag time; scrolling, link selecting, page context menu display, etc. as well as the scroll zoom behavior, and extended page load time, behaving as if the CPU is being maxed out.  

I haven't experienced this on any other web pages.  When I disable Scroll Zoom, all mouse functions return to normal.

I also use Scroll Zoom on Firefox.  No problems with Firefox.

thanks

**Comment by dessant** [comment]
Do you need to zoom with the extenion at least once on the page before everything slows down, or does the issue begin right after page load?

**Comment by nollinvoyd** [comment]
Google is my default search engine.  I just did a search from the address bar.  Then, the first thing I tried I tried was normal scrolling on the page.  The irregular behavior was as I previously described .

**Comment by dessant** [comment]
I've visited this page in Chrome on Windows and scrolling worked as expected: https://www.google.com/search?gl=us&hl=en&gws_rd=cr&q=news

Though scrolling was choppy after the Google Translate popup automatically appeared when the page below was loaded, even if the extension was not present.

https://www.google.com/search?gl=us&hl=es&gws_rd=cr&q=news

**Comment by nollinvoyd** [comment]
The clash is with the Ciuvo Price Comparison extension.  Everything is o.k. after I disable it.

https://chrome.google.com/webstore/detail/ciuvo-price-comparison/cbmmkkbjmcidpennbibfkncodjenfpjh

**Comment by dessant** [comment]
Scroll Zoom does not interfere with the page when not in use, and runs a minimal base module on the page. You could contact the developer of that extension, from a quick look it seems to mess with event listeners, and adds an enormous amout of code to every page you load.
