### ISSUE TITLE
Pages scroll while zooming on Chrome

### ISSUE THREAD

**Issue by cmhrky** [dessant/scroll-zoom#2]
**System**

* OS name: Windows
* OS version: 10 x64
* Browser name: Chrome
* Browser version: 76.0.3809.100 x64
* Extension version: 0.3.0

**Bug description**

The page moves up/down at the same time when zooming with the scroll wheel. No problem in Firefox

**Comment by dessant** [comment]
While the page srolls up and down, is the page also zoomed?

**Comment by cmhrky** [comment]
Yes. "Scroll Zoom" is working good but page moving. Chrome's default Ctrl+Mouse Wheel shortcut works correctly.

**Comment by dessant** [comment]
I've closed it by mistake. This appears to be a breaking change in Chrome, the extension worked as expected in previous browser versions.

**Comment by dessant** [comment]
Beginning with Chrome 73 document level wheel event listeners are treated as passive by default, so scrolling could not be canceled while zooming. This can be fixed by explicitly marking event listeners as not passive.

https://www.chromestatus.com/features/6662647093133312

**Comment by dessant** [comment]
Fixed in https://github.com/dessant/scroll-zoom/commit/fb3cd6c7983023d9baffac27916c2f5a74564d10.

**Comment by cmhrky** [comment]
Thanks. Works fine.
