### ISSUE TITLE
Reset zoom level

### ISSUE THREAD

**Issue by cmhrky** [dessant/scroll-zoom#3]
**Is your feature request related to a problem? Please describe.**
Can you add a shortcut to set the default zoom?

**Describe the solution you'd like**
Right click + Left click to to default zoom.

**Comment by dessant** [comment]
Sounds interesting, by default zoom you mean resetting the zoom level to 100%?

**Comment by cmhrky** [comment]
Yes. Default zoom level %100.

**Comment by dessant** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getZoomSettings

**Comment by dessant** [comment]
This feature will be included in the next release, and you'll be able to configure it from the extension's options.

https://github.com/dessant/scroll-zoom/commit/d1f7778698328576c1b32ff46418bf09951bd6df
