### ISSUE TITLE
Not working on all pages

### ISSUE THREAD

**Issue by tbrodbeck** [dessant/scroll-zoom#5]
**System**

* OS name: macOS
* OS version: 10.15.2
* Browser name: Google Chrome
* Browser version: 79.0.3945.88 (Official Build) (64-bit)
* Extension version: 0.4.0

**Bug description**

Nothing works on certain pages like the Chrome Web Store and the options page of the extension (`src/options/index.html`).
**Logs**

There are no logs generated while trying to zoom.

**Comment by dessant** [comment]
This is a limitation of browser extensions, content scripts cannot run on certain pages. There's also a note about this limitation in the description of the Chrome Web Store listing.

> Due to browser limitations the extension does not work on chrome.google.com/webstore or local browser and extension pages, such as chrome://extensions.
