### ISSUE TITLE
Respect increment, max & min settings in about:config in Ffx

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [dessant/scroll-zoom#6]
There are 3 zoom settings in Firefox about:config that it would be nice if this respected. The minimum zoom [I think 30% is the defauult], maximum zoom [I think 300% is the default, but I set mine at 1000%] and a comma delimited string of allowed zoom levels. I set mine with lots of levels, most about 5% apart, so the zooming is less jerky. These settings are respected by control+scroll in the native interface, but oddly, control+plus respects 2 of them, but sets it's own  max at 250. Gofigger.

**Describe the solution you'd like**
I'd be very happy if this behaved exactly like control+scroll.  Blue sky? Well, that comma delimited string of allowed values is limited to a certain length. It would be nice  if it weren't. I'd like smoother scrolling still, but that's not important.

**Describe alternatives you've considered**
I made a pretty nice dash script to use mousebindings and xdotool to do this, but unfortunately Ffx doesn't recognize control+scroll from xdotool. It does recognize control+plus[or minus] but that doesn't have the range.  So my script zooms more smoothly than your extension, but it maxes out at 250% :-[.

**Additional context**
Yours is the best zooming extension in Firefox. I'll tip when I'm not broke. Thanks.

**Comment by dessant** [comment]
Hi, thanks for the detailed feature request! This is a bit of a niche feature, but I think it would be useful to have. Regarding the max zoom level, we may be out of luck there, last time I tested the extension API, it has thrown an error when I've attempted to set a zoom level that is higher than what's possible with built-in zoom in Firefox.

**Comment by dessant** [comment]
We cannot read about:config values, and there is no API for retrieving the default zoom steps of the browser.

What could be done is to just have a text field on the extension's options page that you can fill with a comma delimited list. Feel free to share a string for testing that you'd prefer to use, I'll probably add this feature next week.

**Comment by ThomasSeeker** [comment]
Hey guys, ... I have exactly the same wish!

I just discovered this wonderful little addon and I'm very happy! For years I have been looking for this. The pre-Quantum-Firefox used to have an addon like it ... but not afterwards. ... And I missed it sooo much! :-)

Now like my fellow commenter I just would wish the zooming steps would be configurable. That would be perfect! 

Or is there some config-file somewhere, which I can edit?

Best greetings from Germany!

**Comment by ThomasSeeker** [comment]
Is there a config-file somewhere, which I can edit?

**Comment by dessant** [comment]
You can now customize zoom levels from the extension's options in version 1.1.0, which has been published on Firefox Add-ons.

On Firefox you can add a comma separated list of values ranging from 0.3 to 5, 5 meaning a zoom of 500%.

**Comment by ThomasSeeker** [comment]
Wow!!! ... This works like a charm!
Beautiful! ... Thank you very much!
:-)
