### ISSUE TITLE
Disable Zoom during Highlighting

### ISSUE THREAD

**Issue by ThomasSeeker** [dessant/scroll-zoom#8]
Hey there, 

this is a feature request.

**Is your feature request related to a problem? Please describe.**

I use the left mouse-button for zooming. When I highlight text (also with the left button) and the text is longer than what is shown on the screen, I used to be able to scroll down while highlighting. This was convenient. ... Now this doesn't work anymore, instead the page gets zoomed. 

**Describe the solution you'd like**

I'd like the addon to register, that I want to highlight text (because I already did highlight a lot) and therefore disable the zoom function for this event.

This makes sense, doesn't it?
Do you think, this is possible?

Best greetings,
Thomas

**Comment by dessant** [comment]
> I used to be able to scroll down while highlighting.
You mean without the extension, or with a previous version of the extenaion?

We could ignore the gesture when the primary button is used and there is selected text on the page, but I'm not sure if selecting rather than zooming is always the intention when there happens to be selected text on the page. Maybe an option that is enabled by default could work for everyone.

**Comment by ThomasSeeker** [comment]
> > I used to be able to scroll down while highlighting.
> 
> You mean without the extension, or with a previous version of the extenaion?
> 

Without the extension. 


> We could ignore the gesture when the primary button is used and there is selected text on the page, but I'm not sure if selecting rather than zooming is always the intention when there happens to be selected text on the page. Maybe an option that is enabled by default could work for everyone.

Yes, that sounds like a very good solution! 
And to avoid triggering this feature by accident ... I would suggest making the necessary selected text larger than a whole line. (Because a whole line is sometimes easily highlighted with a mouse-movement of just one pixel.)

**Comment by dessant** [comment]
The extension will ignore the zoom gesture by default during text selection when the primary mouse button is used, and you'll need to select at least one character with the left button before beginning to scroll.

I'm uploading version 2.0.0 to extension stores now, so the update should become available in the next few days.

**Comment by ThomasSeeker** [comment]
Thank you very much!
:-)
