### ISSUE TITLE
Zoom step values

### ISSUE THREAD

**Issue by LSTemp** [dessant/scroll-zoom#9]
**Is your feature request related to a problem? Please describe.**
Addon use default zoom step. I can change it use toolkit.zoomManager.zoomValues, zoom.minPercent and zoom.maxPercent in the about:config.

**Describe the solution you'd like**
If U cant read this changes from about:config - then add zoom values in the addon config (DONT HARDCODE IT!)

**Describe alternatives you've considered**

**Additional context**
Thx 4 addon.

**Comment by dessant** [comment]
This has already been implemented in version 1.1.0. Extensions cannot read about:config values, visit the extension's options to configure the zoom steps to your liking.

https://github.com/dessant/scroll-zoom/issues/6#issuecomment-821823745

**Comment by LSTemp** [comment]
Sorry. I want this & missed with last addon upgrade. ;D Thx.

**Comment by LSTemp** [comment]
Perfect! Another Thx.

Please add for the "Zoom reset gesture" addon option value "Off/None".

**Comment by LSTemp** [comment]
Perfect! Another Thx.

Please add for the "Zoom reset gesture" addon option value "Off/None".

I hhink add about option "browser.zoom.full" to addon option will perfect too.

**Comment by dessant** [comment]
Hi, just wanted to let you know that you can now disable each mouse gesture, make sure to install version 2.0.1 to configure the new feature.
